server:
  port : 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exercise?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl   
logging:
  level:
    '[org.springframework]': ERROR
    '[br.com.wagnerlima85.employees]': DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
